<?php

namespace Database\Seeders;

use App\Models\KarmicLesson;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KarmicLessonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        KarmicLesson::create([
            'ref_number'  =>  1,
            'description'   =>  filter_var("E’ una lezione che riguarda il lato maschile, in relazione quindi con la figura paterna. Ci si trova di fronte ad imparare a essere più determinato, sviluppando maggiore iniziativa nella vita. La volontà deve essere rafforzata. Deve imparare ad essere più indipendente e ha bisogno di affidarsi maggiormente alle sue decisioni. Per questo nella sua vita tenderà ad incontrare persone con un carattere forte, dalle quali potrà trarre esempio e sostegno, ma anche con le quali si scontrerà spesso. Con queste persone sarà messa alla prova la sua capacità di resistenza, nel senso che se non riuscirà a tenere loro testa, tenderanno a prevaricarlo. Queste dinamiche hanno lo scopo di aiutarlo a diventare più forte e dinamico. Dovrà anche affidarsi di più a se stesso, esprimendo le sue opinioni personali, imparando a non preoccuparsi troppo di ciò che gli altri pensano. Per alcuni si tratterà anche di vincere la timidezza o un eccessivo riserbo. Deve quindi lavorare sull’autostima e avere più fiducia nelle sue possibilità e nelle sue capacità di giudizio. Deve imparare anche a vincere l’inerzia, smettendo di rimandare a domani quello che può fare nell’immediato. Altre caratteristiche da prendere in considerazione sono: La sua personalità manca della decisione, dell’aggressività necessaria per aprirsi facilmente un varco fra le normali circostanze negative della vita. Tenderà a farsi soverchiare dagli altri, a porsi in posizione subalterna e a farsi dominare, prima dai genitori, poi dagli amici, dai colleghi, dal coniuge e così via. Sempre timoroso e instabile, esiterà a prendere posizioni decise, a uscire allo scoperto e ad imporre i propri giudizi, con il rischio di sviluppare un grave complesso di inferiorità. Regola: dovrà accrescere la forza di volontà agendo per gradi. In primo luogo esaminare con cura tutti gli aspetti di una determinata questione, prendere con calma la decisione che ritiene opportuna, poi comunicarla agli altri e attienersi ad essa, facendo attenzione a non trasformare il suo atteggiamento, sempre esitante nell’estremo opposto, cioè in una irragionevole ostinazione.", FILTER_SANITIZE_STRING),            'created_at' => now(),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  2,
            'description'   =>  filter_var("E’ una lezione che riguarda il lato femminile, in relazione quindi con la figura Materna. Si dovrà imparare a essere più diplomatico e ad avere più tatto, per salvaguardare le relazioni ed imparare a far parte di un gruppo. inoltre imparare ad ascoltare di più se stessi e sviluppare l’empatia, diventando più sensibili verso i bisogni e sentimenti altrui. Sarà probabile di trovarsi spesso in situazioni che richiedono pazienza e attenzione e dove l’unico modo per avere successo è lavorare in stretta cooperazione con gli altri. da non sottovalutare l’importanza di quei piccoli gesti o di quelle attenzioni che di solito si trovano inutili, ma a che agli altri fanno molto piacere. Sarà da sviluppare il proprio lato femminile, uomo o donna che si sia, significa anche diventare paziente e gentile con se stessi. Altre caratteristiche da prendere in considerazione sono: Il 2 nella lezione karmica indica irrequietezza e impazienza. Si è insofferenti, si pensa di dover essere al centro dell’attenzione e non si sopporta il fatto che gli altri non ci prestano tutto l’ascolto che secondo noi dovrebbero avere. Delle volte si è inclini a credere di essere vittima di una persecuzione deliberata o di un destino malefico, che di volta in volta ci pone in situazioni insopportabili. Di conseguenza, si dimentica ogni buona regola di diplomazia e di civile convenienza, assumendo atteggiamenti incostanti che faranno trapelare la scarsa considerazione per le esigenze del prossimo. Sarebbe opportuno imparare ad essere più impersonale prima di reagire a una determinata circostanza nel proprio modo abituale. Riflettere a quanto successo e prendere in considerazione che forse l’accaduto non era diretto a sè, e proprio per questo non c’è bisogno di lamentarsi. Smettere di provare compassione per le proprie disgrazie e cominciare a pensare che gli altri hanno sentimenti e necessità di cui si dovrebbe tener conto.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  3,
            'description'   =>  filter_var("E’ una lezione che riguarda il senso di identità. Si tende a sottovalutare la propria persona, dando più importanza agli altri che a te stesso. Si tende ad essere molto auto-critici e non si è mai soddisfatti dei propri risultati; ogni volta che ci si trova al centro dell’ attenzione, si riesci a trovare qualcosa che ci mette in imbarazzo o che ci fa sentire inadeguati. È come se si avesse creato nella propria mente un modello di perfezione, che ci rende difficile far coincidere i propri ideali e con la loro possibilità di realizzazione pratica. C’è bisogno di imparare a giocare, prendendosi meno sul serio. Si deve prendere consapevolezza del proprio giudice interno, tenerlo a freno, altrimenti si rischia di non riuscire a coglier l’attimo presente e godersi veramente la vita. Si prendono le cose troppo sul serio. Si dovrebbe sdrammatizzare la vita, provare a essere più ottimisti e allegri, condividendo la propria gioia con gli altri. La vita ci confronterà con situazioni che richiedono comunicazione, creatività e immaginazione. Il numero 3 a volte manca agli artisti dotati di talento, ma che per avere successo dovranno sviluppare perseveranza e consapevolezza sulle loro capacità. Altre caratteristiche da prendere in considerazione sono: Se manca il numero 3 potrebbe significare che non si è dotati di particolari talenti. Magari non si ha una voce intonata, non si sa disegnare bene, non si ha la predisposizione per fare sport, si è impacciati a ballare, e così via. In poche parole manca quella piccola nota distintiva, che altre persone sanno invece sfruttare con successo e portare avanti nella vita. Per questo c’è la tendenza ad isolarsi, a coltivare una certa amarezza di carattere o a sviluppare sentimenti malevoli, che si traducono in un atteggiamento antisociale. Regola: Considerare che non esistono soltanto talenti spontanei, ma anche capacità che si possono acquisire con lo studio e l’applicazione. Scegliere perciò un hobby, coltivalrlo fino a diventare un esperto nel campo, cominciare a fare di questo interesse un oggetto di conversazione per poi passare ad altri e diversificare il più possibile.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  4,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con l’aspetto materiale dell’esistenza. Si è data troppa importanza allo spirito, alla mente o all’intelletto, trascurando l’aspetto pratico delle cose. Per questo adesso manca il senso delle radici e a volte ci si sente confusi nel dare una direzione alla propria esistenza. Si dovrà adottare un approccio metodico e disciplinato. È necessario creare situazioni stabili e dare continuità alle cose, altrimenti si rischia di sentirsi smarriti e propensi a continui cambiamenti destabilizzanti. Si ha problemi a trovare il lavoro che ci soddisfa e gli altri potrebbero vederci con la testa tra le nuvole. Anche una spinta irresistibile a cambiare lavoro potrebbe derivare dall’insofferenza verso la routine. Si potrebbe scoprire troppo presto che il nuovo lavoro non ci dà le emozioni che ci si aspettava e che anzi richiede ancora più impegno e perseveranza. questo può spingere a rinunciare troppo presto. Ci si troverà per questo impegnati in lavori che richiedono organizzazione, disciplina e concentrazione. Altre caratteristiche da prendere in considerazione sono: Il numero 4 mancante rende la persona incapace di applicarsi con costanza e profitto ad un qualsiasi compito. La concentrazione sul lavoro, la cura dei particolari, la precisione necessaria sembra una cosa insopportabile. Quando occorre classificare qualcosa o fare una serie di preparativi per mettere a punto una operazione qualsiasi ci si ritrova immersi nel caos. Qualsiasi tipo di routine, anche a livello personale, sembra inconcepibile, di conseguenza questo porta a condurre una vita sregolata che si può ripercuotere sul proprio stato di salute. A tutto ciò si aggiunge una costante insoddisfazione psichica perché ci si vede incapaci di portare a termine un progetto, oppure perché è impossibile ottenere tutto e subito come si vorrebbe. Questo atteggiamento potrebbe finire con l’instaurarsi di uno stato di frustrazione che può assumere aspetti patologici. Regola: ci si dovrebbe convincere che i successi raggiunti nel modo più difficile sono quelli che danno maggiore soddisfazione. Il sacrificio talvolta è auspicabile, di per se stesso, perché accresce la gioia al momento della vittoria finale. Evitare i lavori troppo noiosi e metodici per i quali non si è portati. Non considerare il lavoro in sè come una maledizione eterna, ma pensare piuttosto ai benefici che comporta.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  5,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con l’adattabilità e il cambiamento. Si è coltivato uno stile di vita molto rigido, retto da regole restrittive. Adesso si deve superare la paura di vivere. Ha bisogno di diventare più libero e avventuroso, cogliendo svariate opportunità di fare esperienza: viaggiando, esplorando paesi e usanze diversi, incontrando nuove persone, anche caratterialmente molto dissimili da sè. Si deve ampliare la mappa mentale, allargare la vedute, essere più socievole, imparare a fluire con l’esistenza, accettando il cambiamento. Ci si dovrà adeguare a nuove circostanze e si sarà messi alla prova. Si dovrà superare la tendenza ad essere rigidi e inflessibili, la lezione di vita è quella di imparare ad avere fede. Si potrà crescere molto attraverso l’esperienza, lìimportante è fluire con la vita, adattarsi ai cambiamenti, stare al passo con il ritmo delle cose, ricordando che esistono molti modi diversi per arrivare a uno stesso risultato. Altre caratteristiche da prendere in considerazione sono: Il numero 5 mancante indica che si tende a sfuggire dall’esperienza della vita. Si può essere una persona intollerante nei confronti di quanti mostrano di godere dell’esistenza o di trarre piacere dalle circostanze. Nelle vicissitudini personali, la mancanza del 5 può rendere una persona con scarsa capacità di immaginazione, di conseguenza non riuscire a sentirsi coinvolti nelle esperienze degli altri e tendere a chiudersi in se stessi per meditare sulle disgrazie personali. Si temono le novità e i cambiamenti sia di prospettiva che di ambiente. Agli eventi improvvisi e il trovarsi in compagnia possono essere esperienze poco piacevoli, purtroppo anche i rapporti con l’altro sesso sono sovente causa di tormento più che di soddisfazione. Regola: ci si dovrebbe abituare a prendere le cose così come vengono, senza farne un dramma su tutto ciò che accade. Cercare di comprendere le debolezze e le mancanze di coloro che ci circondano perché nello stesso tempo capiremo meglio anche noi stessi. Non tirarsi indietro da situazioni che a prima vista ci sembra di non poter affrontare. Prima studiare con attenzione tutte le circostanze e soltanto dopo scegliere se conviene rimanere in disparte.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  6,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con le relazioni e i sentimenti. Si è coltivata una visione molto mentale, staccandosi dal mondo delle emozioni, come autodifesa per non soffrire. Per questo si potrebbero avere problemi con l’assumersi responsabilità che coinvolgono altre persone. Le relazioni affettive o sentimentali potrebbero rappresentare la spina nel fianco, si devie imparare a mostrare le proprie vere emozioni. Può succederte di sentirsi isolati e soli, anche senza un vero motivo, ma la spiegazione può risiedere nel fatto che si sono elevate pesanti barriere di controllo sui rapporti nterpersonali, e anche involontariamente si fatica a sentirsi veramente coinvolti. Questo può rendere il legame con gli altri distaccato o superficiale. Anche il matrimonio e altre importanti relazioni, possono risentire di questi conflitti interni. Si deve imparare l’importanza di una stretta e duratura relazione con gli amici. Le relazioni, sono un po’ come le piante, vanno innaffiate e nel caso specifico, coltivate. Per poter essere più felici si dovrà imparare a dare, mettendosi finalmente in gioco e smantellando il filo spinato delle barriere emozionali. Altre caratteristiche da prendere in considerazione sono: L’assenza del numero 6, che è il numero dell’adattabilità, indica l’incapacità di entrare in sintonia con un determinato ambiente, di adeguarsi alle situazioni che cambiano e si evolvono, di affrontare con elasticità mentale le mutevoli circostanze della vita. Si è una persona che si sente oppressa dalle responsabilità e dai vincoli familiari, dalle limitazioni, dalla liberta di movimento derivante dal lavoro, dal contesto sociale o dalle condizioni economiche. Spesso non si riesce a completare le imprese iniziate dando di ciò la colpa al destino, oppure a seconda dei casi al tempo che manca, al denaro, alla concentrazione insufficiente, che sarebbe necessaria per svolgere quel determinato lavoro. Regola: ci si dovrebbe abituare ad apprezzare prima le cose piacevoli che sono intorno a noi e soltanto dopo considerare anche quelle che non ci piacciono. Cominciare a guardare coloro che la vita ci pone di fronte, non come persone che ci ostacolano ma come esseri che potrebbero aiutarci in quello che facciamo.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  7,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con l’introspezione e l’approfondimento dei vari aspetti dell’esistenza. Si è coltivata una visione molto pratica e razionale, dedicando poco tempo a conoscere te stesso. Manca la volontà o la determinazione di dedicarsi a un’autoanalisi costruttiva, che può aiutare a migliorare se stesso o a esprimere un determinato talento che si possiede. Ha bisogno di esaminare le sue conoscenze e le sue inclinazioni, perché ci sono delle capacità potenziali che sta trascurando. Può scoprirle, osservando le sue amicizie o le tue relazioni, forse qualcuno che conosce bene, e col quale ha un rapporto conflittuale, esprime proprio quel lato di sè, dal quale sarà affascinato, ma che al contempo reprime. Deve imparare ad essere critico con se stesso, senza condanna, ma al fine di realizzare il suo potenziale. Imparare a dedicare un po’ di tempo alla meditazione, lo aiuterà a prendere confidenza col suo mondo interiore. Altre caratteristiche da prendere in considerazione sono: Essendo il numero 7 il numero del misticismo, la sua mancanza indica che la sua personalità non prova alcun interesse per questo argomento e anzi, considera un certo fastidio per ogni tipo di espressione religiosa, filosofica o metafisica con cui può venire in contatto. Dal punto di vista psicologico l’assenza del 7 rivela la sua tendenza a soffocare le emozioni o comunque a non mostrarle all’esterno, rivelandole alle persone che gli stanno accanto. Cerca di costruire una maschera di impassibilità, rifugge dai contatti umani e tende a ritirarsi nel suo angolo di solitudine. Tuttavia nel profondo, desidera fortemente l’amore, l’amicizia, e prova un disperato bisogno di essere apprezzato e compreso. Questo tipo di comportamento indica una timidezza eccessiva, di tipo esagerato, come pure orgoglio. Alla radice c’è comunque il timore di vedere le proprie emozioni, di esprimerle per la paura di non essere preso in considerazione o di essere deriso. In questo modo però non fa altro che innalzare una barriera che impedisce i contatti sociali e che spesso favoriscono l’evasione nelle varie dipendenze. Regola: si deve abituare poco a poco a vincere l’introversione mettendo in mostra i suoi talenti con i mezzi del quale è sicuro. Procedere per gradi fino a quando si è certi che la più profonda emozione non potrà indurre a sbagliare, non esitare più a mostrarsi; esprimere le sue opinioni, cercare il dialogo con argomenti nei quali sa di essere un esperto e di poter fare bella figura. Studiare le dottrine esoteriche almeno per curiosità, se non altro per imparare che nell’anima umana ci sono tante ricchezze e risorse nascoste da consentire il superamento di qualsiasi ostacolo.", FILTER_SANITIZE_STRING),            'created_at' => now(),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  8,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con il denaro e con il potere personale. Per vari motivi, ha limitato le sue capacità di avere successo nel mondo materiale. Questo non significa che non sia capace di attirare anche notevoli quantità di denaro ed essere un buon affarista, ma nelle sue attività finanziarie si verificano grandi alti e bassi, dovuti in gran parte a causa della mancanza di oculatezza nel maneggiare le proprie risorse. È molto indipendente e non accetta facilmente consigli su come migliorare l’andamento della sua vita. Può avere problemi a gestire importanti somme di denaro. Ciò deriva da una forma di presunzione del tipo “nessuno deve insegnarmi nulla”. Questo atteggiamento ostinato, che impedisce di conoscere i suoi limiti, può frenare la sua evoluzione. Per questo dovrà imparare a gestire o a far fruttare il suo denaro e le sue risorse, evitando al denaro di scivolare attraverso le dita. Altre caratteristiche da prendere in considerazione sono: L’incubo della personalità che è priva del numero 8, è quello di finire in povertà, senza mezzi né risorse. Si regola di conseguenza, non soltanto nei confronti degli altri, ma soprattutto con loro stessi. Può giungere a privarsi di tante cose, fuorché dello stretto necessario, per il timore che il denaro non gli basti mai. Talvolta può essere vero, altre volte invece è esattamente l’opposto. È incapace di resistere alla tentazione di spendere e nel contempo di conservare il denaro. Il fatto che l’8 è il numero che rappresenta l’oculatezza, nelle questioni finanziarie, se ne è privo può essere che non sa riconoscere il valore esatto del denaro e, a seconda del carattere, esageratamente attaccato ad esso o avrà inclinazione a spendere senza motivo. Regola: In primo luogo, deve convincersi che, nel bene o nel male, il denaro non è tutto. Esistono altri valori di cui occuparsi e ai quali dedicarsi. Fare appello alla propria fantasia per sperimentare che in certi casi la felicità può essere ottenuta anche in modo diverso che comprandola con contanti. Questo è il primo passo verso il raggiungimento di un certo equilibrio, che poi sopraggiungerà automaticamente.", FILTER_SANITIZE_STRING),

        ]);

        KarmicLesson::create([
            'ref_number'  =>  9,
            'description'   =>  filter_var("E’ una lezione che riguarda il rapporto con le emozioni e con la tolleranza. Si sono sviluppate delle corazze per difendersi dalla cattiveria del mondo. Deve imparare a essere più compassionevole, generoso, e comprensivo. Deve imparare a sviluppare più empatia, identificandosi maggiormente con le prove e con le sofferenze degli altri. A volte tende a rimuovere le cose per non soffrire e questo agli occhi altrui, viene visto come indifferenza o addirittura cattiveria. Il suo buon cuore potrebbe venire facilmente frainteso. Ci saranno momenti in cui dovrà sacrificare le sue ambizioni o il suo egocentrismo a favore di progetti che tengano conto del bene degli altri. Deve imparare ad ampliare il suo punto di vista, per vedere le cose da una prospettiva più ampia, centrata nel cuore. Non si rende conto delle enormi potenzialità di cui dispone e che possono influenzare positivamente il suo destino e quello degli altri. Deve superare la paura di impegnarsi a favore della comunità e del genere umano, lasciando andare quelle antiche paure di annientamento che vengono dal suo passato arcaico. Pertanto è positivo il suo impegno a favore di una determinata causa sociale. Altre caratteristiche da prendere in considerazione sono: Il numero 9 rappresenta il numero dei valori umani e dell’altruismo. Se la griglia ne è priva significa che la sua personalità è troppo sbilanciata verso se stessa e poco aperta ai rapporti con gli altri. Potrebbe essere una persona cupa, poco propensa a frequentare compagnie leggere o scherzose, indifferente alla gioia quanto alla sofferenza degli altri. La sua paura più grande è quella di venire coinvolto in fatti che non lo riguardano, per questo spesso rinuncia a conoscenze e rapporti che pure in qualche modo desidera. Difficilmente concede l’aiuto e altrettanto difficilmente lo chiede. Regola: Deve imparare ad esprime interesse, prima con le persone verso le quali prova reamente questi sentimenti, per poi cominciare ad interessarti delle sorti, non soltanto di individui, ma anche di gruppi e classi sociali. Potrebbe iniziare iscrivendosi a qualche associazione umanitaria o a qualche ente di beneficenza. Aiutando il prossimo attivamente ne sarà pagato con un senso di accresciuta ricchezza interiore.", FILTER_SANITIZE_STRING),

        ]);
    }
}
